### ISSUE TITLE
banglejs2: altimeter broken after extended use

### ISSUE THREAD

**Issue by pavelmachek** [espruino/BangleApps#3096] opened 2023-11-14 20:53 UTC
### Affected hardware version

Bangle 2

### Your firmware version

2v19

### The bug

After extensive use, altimeter locked up. Unfortunately, neither reboot nor complete draining of battery fixed the issue. After some more experiments, google revealed following snippet:

````
{
  // Show the menu                                                              
  E.showMenu({
    "" : { "title" : "Barometer reset" },
    "Reset" : () => {
      if (Bangle.barometerRd(0x0D) == 16) {
        Bangle.barometerWr(0x0c, 9);
        E.reboot();
      }
      back();
    },
  });
}

````

Which indeed fixed the issue. I believe we should be reseting barometer at each boot, working with persistent issues is not fun.

**Comment by bobrippling** [comment] 2023-11-14 21:49
Yes - I believe this is a duplicate of #3086 and I guess you found the code from the [forum post](https://forum.espruino.com/conversations/373620/)? I'll close this as a duplicate but feel free to reopen or comment on the other issue if you see problems after the changes listed there

**Closed by bobrippling** 2023-11-14 21:49 UTC
