### ISSUE TITLE
messages app

### ISSUE THREAD

**Issue by akeeganmac** [espruino/BangleApps#988] opened 2021-12-03 02:03 UTC
Could the app remove read messages on disconnect? If I move out of range of my phone, all the previous messages are brought back as new, unread, as soon as the watch reconnects (iOS 15.1).

**Comment by mabuchner** [comment] 2021-12-03 07:38
Duplicate of #968 and I yes, this is very annoying.

**Comment by gfwilliams** [comment] 2021-12-03 09:24
> Could the app remove read messages on disconnect? 

It does already remove unread messages on disconnect because someone else wanted this, but that is actually what is causing this issue :(

As mentioned - a duplicate of #968 so closing this

**Closed by gfwilliams** 2021-12-03 09:24 UTC
