### ISSUE TITLE
Sleep log - gadget bridge intergration

### ISSUE THREAD

**Issue by 32bitx64bit** [espruino/BangleApps#3509] opened 2024-07-13 23:47 UTC
### Affected hardware version

Bangle 2

### Your firmware version

2v23

### The bug

Having the ability to see my sleep log in gadget bridge would be huge. And make the app more 100x more useful. As I can just have everything located in one unified spot. Not having to switch between gadget bridge and the app installer to see logs. Or not having to switch through apps on my watch.

**Comment by thyttan** [comment] 2024-07-14 04:24
Duplicate of #3275. See discussion there.

**Closed** 2024-07-14 04:25 UTC
