### ISSUE TITLE
Alarm: Can not leave the repeat custom menu

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#1904] opened 2022-06-01 08:20 UTC
with alarm 0.29 and sched 0.11 on Bangle JS2:
how to Reproduce:
1. open alarm app
2. select new->Alarm
3. select Repeat, choose Custom, select/unselect days to repeat
4. With hardware button go to previous menu. Interface is now frozen.

Error in console:
> Uncaught Error: Unknown Watch 1
 at line 1 col 13
clearWatch(n);Bangle.removeListener("touch",l);g.reset().cle...
            ^
in function "remove" called from line 1 col 139
....back&&WIDGETS.back.remove();Bangle.btnWatches&&(Bangle.btnW...
                              ^
in function called from line 15 col 809 in .boot0
sui(mode,cb);if(!mode)return;if("object"==typeof mode)mode=mode.mode;if(!mo...
                          ^
at line 15 col 809 in .boot0
sui(mode,cb);if(!mode)return;if("object"==typeof mode)mode=mode.mode;if(!mo...
                          ^
in function "setUI" called from line 3 col 212
...<=b)&&b<d.c&&d.select(b))}});return e
                              ^
in function called from line 7 col 80
...em(a)}}};s=E.showScroller(n);return r
                              ^
at line 7 col 80
...em(a)}}};s=E.showScroller(n);return r
                              ^
in function called from line 31 col 16 in alarm.app.js
E.showMenu(menu);
               ^
at line 31 col 16 in alarm.app.js
E.showMenu(menu);
               ^
in function called from system

@alessandrococco you might want to take a look

**Comment by alessandrococco** [comment] 2022-06-01 12:39
@nxdefiant I just tried but I can't replicate the bug :-/ I'm on firmware **2v13.87**. What version are you on?

**Comment by alessandrococco** [comment] 2022-06-01 12:51
> Don't know how to get the minor version (if there is any).

You can see the full version in the About app or you can connect your Bangle to the WEB IDE.

![image](https://user-images.githubusercontent.com/2331798/171408267-b0ab812d-ae34-4b4d-b665-6b996f693b9e.png)

> Did you test with the official version in the app loader or your own version? 

Official app loader.

---

Bangle 1 or 2?

**Comment by nxdefiant** [comment] 2022-06-01 15:01
Update: Only happens when using the button to go to previous menu, not with the back widget.

**Comment by nxdefiant** [comment] 2022-06-01 15:37
Traceback in original post goes to firmware. Updated to "Cutting Edge" Firmware 2v13.123, issue persist.
@gfwilliams Do you have an idea here?

**Comment by gfwilliams** [comment] 2022-06-06 11:19
Do you have any other widgets/boot code installed? I'm just wondering whether something **else** calls `clearWatch` which would end up removing *all* watches on all pins, and would give this error.

**Comment by alessandrococco** [comment] 2022-06-08 19:41
> Update: Only happens when using the button to go to previous menu, not with the back widget.

Yes, now I can replicate it (sorry for being late 😅)

> Do you have any other widgets/boot code installed? I'm just wondering whether something **else** calls `clearWatch` which would end up removing _all_ watches on all pins, and would give this error.

Nope.  
I did some test. I removed all the apps and I installed only boot, launch, antonclk, setting, sched, alarm and the problem is still here ( 2v13.156)

**Comment by gfwilliams** [comment] 2022-06-09 08:50
Tested here and latest cutting edge build should be fixed.

**Closed** 2022-06-09 08:50 UTC

**Comment by alessandrococco** [comment] 2022-06-09 09:49
> Tested here and latest cutting edge build should be fixed.

Thank you, I'll update later!
