### ISSUE TITLE
messages app doesn't show messages randomly

### ISSUE THREAD

**Issue by andiohn** [espruino/BangleApps#1584] opened 2022-03-17 13:18 UTC
Randomly does not show anything in the messages window. I'm using the dark background theme and the text area will stay white sometimes. The title will show correctly.

**Comment by gfwilliams** [comment] 2022-03-17 13:30
Sorry, but this is no use to me whatsoever. You've completely ignored the template for bugs and provided me with basically zero information.

I can't reproduce this so closing.

**Closed by gfwilliams** 2022-03-17 13:30 UTC
