### ISSUE TITLE
authentiwatch pc tool not sending tokens to watch

### ISSUE THREAD

**Issue by Izaic** [espruino/BangleApps#941] opened 2021-11-24 08:24 UTC
When I click the button to upload the tokens to the watch, it shows a loading bar on the bottom for a split second and then nothing happens.

**Comment by m-p-3** [comment] 2021-11-24 16:23
Same here when pairing through mobile (Android 11, using Bromite 95.0.4638.99 as the web browser), the app still says *No tokens* after sending to watch.

**Comment by Smooklu** [comment] 2021-11-27 03:01
Same issue here.

**Comment by andrewgoz** [comment] 2021-11-30 10:00
I'm the author. Until I get an actual Bangle (it's on the way) I can't test the loading/saving of tokens. Other than waiting until I can look at it, another developer might be able to tell me what I'm doing wrong?

**Comment by Smooklu** [comment] 2021-11-30 15:04
> I'm the author. Until I get an actual Bangle (it's on the way) I can't test the loading/saving of tokens. Other than waiting until I can look at it, another developer might be able to tell me what I'm doing wrong?

I can submit the error message I get from the app.

**Comment by Smooklu** [comment] 2021-11-30 15:06
```
Uncaught TypeError: If specifying an object, it must be of the form {data : ..., count : N} or {callback : fn} - got {
  "algorithm": "SHA1",
  "digits": 6, "period": 30,
  "issuer": "",
  "account": "",
  "secret": "JBSWY3DPEHPK3PXP",
  "label": "token"
 }
 at line 1 col 161
...EHPK3PXP","label":"token"}])
```

**Comment by Smooklu** [comment] 2021-11-30 15:13
It looks like the issue is from `interface.html` and not `app.js`.

**Comment by andrewgoz** [comment] 2021-11-30 16:50
Fixed in #972 (checked on my Bangle which turned up while I was at work). It turns out the library Puck.write() has particular structure requirements...

**Comment by gfwilliams** [comment] 2021-11-30 17:14
Ahh - it might actually be that you needed `Storage.writeJSON` and not just `.write` since if you give that an array it assumed it's binary?

**Comment by m-p-3** [comment] 2021-12-04 03:03
Just FYI, I tried pushing a token today to my Bangle.js2 and it worked 🎉

**Comment by Smooklu** [comment] 2021-12-04 03:17
It worked for me too! but I am having a another issue now.

**Comment by Smooklu** [comment] 2021-12-04 03:18
![20211203_211705](https://user-images.githubusercontent.com/37220586/144695052-d49f586e-9107-4121-9c87-6c8d20ca6589.jpg)

**Comment by Smooklu** [comment] 2021-12-04 03:18
When I open the app, I see "Loading..." and then a blank screen with widgets loaded.

**Comment by Smooklu** [comment] 2021-12-04 03:24
When I save a token to the watch, it reports `undefined` in the console. Possibly a issue?

**Comment by Smooklu** [comment] 2021-12-04 03:24
```
{"tokens":[{"algorithm":"SHA1","digits":6,"period":30,"issuer":"","account":"","secret":"JBSWY3DPEHPK3PXP","label":"TEST"}],"misc":{}}
```

**Comment by Smooklu** [comment] 2021-12-04 03:27
If I try installing the app without saving a token, it says `No tokens`  which is expected.

**Comment by andrewgoz** [comment] 2021-12-04 14:11
"No tokens" is the only text where I don't explicitly set the text colours. For everything else I use the defined theme colours. Try changing the theme and see if the text appears. You could also try viewing the theme in the IDE:

`>g.theme`
`={ fg: 0, bg: 65535, fg2: 31, bg2: 2047,`
`  fgH: 0, bgH: 2047, dark: false }`

Could you also try the following in the IDE console:

`>require("Storage").writeJSON`
`=function () { [native code] }`

**Comment by andrewgoz** [comment] 2021-12-16 02:58
Just a note that in #981 I switched to the recommended `Storage.readJSON` and `Storage.writeJSON`. I now consider this issue closed. Whatever is happening with @Smooklu is a separate issue.

**Closed** 2021-12-16 04:04 UTC
